spring:
  application:
    name: eureka-server-peer1
  security:
    basic:
      enabled: true
    user:
      name: username123   #login username
      password: password123

server:
  port: 8761
  max-threads: 2000
  max-connections: 2000

eureka:
  instance:
    hostname: localhost
    appname: eureka-server-appname-1
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false #是否向注册中心注册自己
    fetch-registry: false
    service-url:
      defaultZone: http://username123:password123@${eureka.instance.hostname}:${server.port}/eureka #把Eureka注册到哪个Eureka
    instance:
      prefer-ip-address: true
      instance-id:  ${spring.application.name}:${spring.application.instance_id:${server.port}}

management:
  security:
    enabled: false
