spring:
  application:
    name: eureka-server

server:
  port: 8762
  max-threads: 2000
  max-connections: 2000

eureka:
  instance:
    hostname: peer2
    appname: eureka-server-appname-2
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true #是否向注册中心注册自己
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8761/eureka/ #把Eureka注册到哪个Eureka
    instance:
      prefer-ip-address: true
      instance-id:  ${spring.application.name}:${spring.application.instance_id:${server.port}}

# 安全认证的配置
security:
  basic:
    enabled: false
  user:
    name: root  # 用户名
    password: root   # 用户密码

management:
  security:
    enabled: false
endpoints:
  refresh:
    enabled: true