spring:
  application:
    name: eureka-server
  security:
    user:
      name: username123
      password: password123

server:
  port: 8762
  max-threads: 2000
  max-connections: 2000

eureka:
  instance:
    hostname: localhost
    appname: eureka-server-appname
  client:
    register-with-eureka: false #是否向注册中心注册自己
    fetch-registry: false
    service-url:
      defaultZone: http://username123:password123@/${eureka.instance.hostname}:${server.port}/eureka #把Eureka注册到哪个Eureka
    instance:
      prefer-ip-address: true

management:
  security:
    enabled: false
