server:
  port: 3600
management:
  security:
    enabled: false
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuhaibao324/08demo.spring-cloud-netflix-1
          search-paths: config-repo
eureka:
  client:
    serviceUrl:
      defaultZone: http://username123:password123@localhost:8762/eureka/